steps:
  - name: "golang"
    entrypoint: "go"
    args: ["build"]
    id: "build"

  - name: "alpine"
    entrypoint: /bin/sh
    args:
      - "-c"
      - |
        cat << EOF >> app.yaml
        env_variables:
          KEYGEN_API_KEY: $_KEYGEN_API_KEY
        EOF

  - name: "alpine"
    args: ["cat", "app.yaml"]

  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - "app"
      - "deploy"
      - "--project=$PROJECT_ID"
    waitFor: ["build"]
